apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ "{{ .Values.namespace }}" }}
  name: "autoscaler-{{ "{{ .Values.serviceName }}" }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ "{{ .Values.serviceName }}" }}
  minReplicas: {{ "{{ .Values.minReplicas }}" }}
  maxReplicas: {{ "{{ .Values.maxReplicas }}" }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ "{{ .Values.cpuUsePercentageToReplica }}" }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ "{{ .Values.memUsePercentageToReplica }}" }}
