apiVersion: v2
name: "{{.Inputs.service_name}}"
description: "Chart para inicializar el servicio de {{.Inputs.service_name}}"
appVersion: "Primera version de servicio {{.Inputs.service_name}}"
version: 0.0.1
maintainers:
  - name: Patricio Ascencio
    email: patricio.ascencio@karibu.cl
