namespace: {{kubernetes_namespace}}
own: {{kubernetes_owner}}
app: {{kubernetes_app}}

serviceName: {{service_name}}
serviceAccountName: {{service_account_name}}
gatewayName: {{kubernetes_gateway_name}}
port: 3000
requiredEnvVariable: DELETE_ME

imageName: {{image_name}}

minReplicas: 1
maxReplicas: 1
cpuUsePercentageToReplica: 80
memUsePercentageToReplica: 80

requestCpu: 0
requestMem: 0
limitCpu: 0
limitMem: 0

healthCheckPolicy:
  checkIntervalSec: 60
  timeoutSec: 30
  healthyThreshold: 1
  unhealthyThreshold: 3
  logConfig:
    enable: true

probes:
  path: /health
  startup:
    failureThreshold: 5
    periodSeconds: 30
    timeoutSeconds: 30
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 1
    timeoutSeconds: 30
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 30
    successThreshold: 3
    failureThreshold: 2
    timeoutSeconds: 30